package com.tidelet.app.data.db

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.cash.turbine.test
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class CravingEventDaoTest {

    private lateinit var db: TideletDatabase
    private lateinit var dao: CravingEventDao

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        db = Room.inMemoryDatabaseBuilder(context, TideletDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = db.cravingEventDao()
    }

    @After
    fun tearDown() { db.close() }

    @Test
    fun insert_returnsAutoGeneratedId() = runTest {
        val id1 = dao.insert(CravingEvent(tool = SosToolKey.BREATHE, outcome = CravingOutcome.GOT_THROUGH))
        val id2 = dao.insert(CravingEvent(tool = SosToolKey.REASONS, outcome = CravingOutcome.GOT_THROUGH))

        assertThat(id1).isGreaterThan(0L)
        assertThat(id2).isGreaterThan(id1)
    }

    @Test
    fun observeAll_ordersByTimestampDesc() = runTest {
        dao.insert(CravingEvent(timestampEpochMillis = 1_000L, tool = "a", outcome = "x"))
        dao.insert(CravingEvent(timestampEpochMillis = 3_000L, tool = "b", outcome = "y"))
        dao.insert(CravingEvent(timestampEpochMillis = 2_000L, tool = "c", outcome = "z"))

        dao.observeAll().test {
            val rows = awaitItem()
            assertThat(rows.map { it.timestampEpochMillis }).containsExactly(3_000L, 2_000L, 1_000L).inOrder()
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun countByOutcome_filtersByOutcomeString() = runTest {
        dao.insert(CravingEvent(tool = "a", outcome = CravingOutcome.GOT_THROUGH))
        dao.insert(CravingEvent(tool = "b", outcome = CravingOutcome.GOT_THROUGH))
        dao.insert(CravingEvent(tool = "c", outcome = CravingOutcome.DRANK))

        assertThat(dao.countByOutcome(CravingOutcome.GOT_THROUGH)).isEqualTo(2)
        assertThat(dao.countByOutcome(CravingOutcome.DRANK)).isEqualTo(1)
        assertThat(dao.countByOutcome(CravingOutcome.STILL_STRUGGLING)).isEqualTo(0)
    }
}
